name: Build and Deploy

on:
  push:
    branches:
      - master
      - feature

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install html-validator-cli
        run: npm install -g html-validator-cli

      - name: Validate index.html
        run: html-validator --file=index.html --verbose

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-html
    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ env.BRANCH }}-latest .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ env.BRANCH }}-latest

  github-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./


