name: Deploy Lab 3

on:
  push:
    branches:
      - master
      - feature

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0

  docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:master-latest .

  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker Image
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")
          docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${BRANCH}-latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${BRANCH}-latest

  github-pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./


